---
title: "WritingExercise02"
---

# Instructions

Each of the writing samples below violates at least one of Strunk and White’s Principles of Composition. Read the samples critically, and edit to improve them. Remember to make a commit to save your changes when you are done. 

# Writing Samples

## Principle: use the active voice

Scientists performed an analysis to understand the metabolic pathways in bacteria.

## Put statements in positive form.

Bacteria that metabolize glucose are important for fermentation.

## Use definite, specific, concrete language.

Algae can be useful in biofuel production (Zhang et al, 2016).

## Omit needless words

Research have shown metabolic pathways of Aspergillus niger can be engineered to increase production of citric acid; a key ingredient in industrial applications. 

## Express coordinate ideas in similar form.

Microbes are used to produce fermented foods e.g., yeast for bread and alcohol, lactic acid bacteria for pickles and cheese. Fermentation is important for coffee and chocolate production.


## Keep related words together.

Bacteria microbes such as Ideonella sakaiensis are able to degrade plastics such as polyethylene (PET) using specific enzymes (e.g. PETase). 

## In summaries, keep to one tense.

The engineered *E. coli* strain was grown in a 5 L bioreactor for 24 hours. 
During this period, the glucose concentration decreased steadily, while the optical density increased from 0.2 to 8.4. At the end of the fermentation, the culture was harvested by centrifugation and the recombinant enzyme purified using affinity chromatography. 
The purified enzyme showed a specific activity of 42 U/mg and therefore suitable for use in the subsequent biocatalytic process.

## Place the emphatic words of a sentence at the end.
 
Genomic data suggests that any given species of Streptomyces can produce a wide variety of antibiotics.

