---
title: "WritingExercise05"
---

# Reflect on your own skills and development as a writer

- What are the areas you think you are good at? Where can you improve?
Good at conscise language and clarity in writing. Could improve on grammar and punctuation.
- How will you further develop your skills over the coming year? Can you make a specific, detailed plan?
Devleop skills through reading more scientific literature to understand appropriate language and grammar habits.
# Reflect on writing more generally
Writing can be interpreted differently however good writing always follows similar style and rules. I can struggle to compose my thoughts in an articulated way.
- What principles of composition discussed today did you find most useful?
Clarity and consciseness in language. Learning when to cut words and when to expand.
- If you were going to formulate your own writing rules, what would they be?
Expand on facts for clarity not for sake of it. If something can be enhanced with examples always include. Stick to aim of writing and don't ramble and include unnecessary information.
# Commit your reflections to writing
I will take opportunities to reflect on own writing to check for mistakes or enhancements. I will make use of others to gain a different perspective on my writing.
Compose a paragraph summarizing your reflections. Remember to use the "commit" process to save your changes when you are finished.
Writing is best understood when clear and easy to follow. Themes should be grouped together and stick to the aim without unnecessary rambling. Editing can always improve work but best with a fresh perspective. Writing facts alone isn't enough if not understandable to the reader. 
